// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48FfdB843PoFMYAtkqdYjSarun6Kpfhc',
    appId: '1:562917262792:web:6d8ef03a59a642d896acfd',
    messagingSenderId: '562917262792',
    projectId: 'music-affect-data-osu-ecampus',
    authDomain: 'music-affect-data-osu-ecampus.firebaseapp.com',
    storageBucket: 'music-affect-data-osu-ecampus.appspot.com',
    measurementId: 'G-FX4XEHDS6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3fVsxkvSxNQ7PfuPPp_m8a93oZt8UmA',
    appId: '1:562917262792:android:7403316d7bdf85b396acfd',
    messagingSenderId: '562917262792',
    projectId: 'music-affect-data-osu-ecampus',
    storageBucket: 'music-affect-data-osu-ecampus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoSm0jDvx19FcBrk44PnIaJvR5L23a-SY',
    appId: '1:562917262792:ios:610b5abf7cad852996acfd',
    messagingSenderId: '562917262792',
    projectId: 'music-affect-data-osu-ecampus',
    storageBucket: 'music-affect-data-osu-ecampus.appspot.com',
    iosClientId: '562917262792-2vgmaq8v9fn58d2umnlc0b0jcq01mvbc.apps.googleusercontent.com',
    iosBundleId: 'org.soundbendor.flutterApp',
  );
}
